effects = {

category: "Effects & UI",

dir: 'effects-ui',

folders: [
"aristo",
"blur.js",
"captify",
"capty",
"champagne",
"collapse",
"colortips",
"content.hover",
"context.menu",
"expando",
"flicker",
"flip",
"fullscreen.js",
"gips.tooltips",
"gloss",
"gradienter",
"icheck",
"innerfade",
"isotope",
"jfontsize",
"joyride",
"jqcloud",
"jquery.mobile.flat.ui.theme",
"jquery.ui.bootstrap",
"jrumble",
"jshaker",
"meow",
"message-bar",
"minibar",
"mobile.bootstrap",
"nestable",
"pie-menu",
"pointpoint",
"popover",
"powertip",
"quovolver",
"smart.slider",
"snotify",
"sweet-tooltip",
"switchy",
"tipsy",
"totem-ticker",
"verbose-calendar",
"wookmark"
],
    
url: function(){return function(text,render){text=render(text);var url=plugins;return'<a class="btn btn-primary btn-large btn-warning sub-menu" href="'+url+''+text+'">'+capitaliseFirstLetter(text)+'</a>'}}

};
